#!/usr/bin/python

import os
import sys
import db
import browse

######################################################################
# Main.

if len(sys.argv) < 2:
    print "Usage: %s path" % ( sys.argv[0] )
    sys.exit(1)

# Need to connect before using the database.
db.connect(None)

path = os.path.abspath(sys.argv[1])

browse.update_toplevel_path_disk_usage(path)

