#!/usr/bin/env python2.4

import psycopg2
import db
import os.path

db.connect(None)
dirs = db.get("select path_id,path from filesystem_info")
for path in dirs:
    path_name = path[1]
    path_id = path[0]

    ppath_name = os.path.dirname(path_name)
    ppath_id = db.get1("select path_id from filesystem_info where path = %(ppath_name)s", vars())

    if ppath_id:
        ppath_id = ppath_id[0]
        db.do("update filesystem_info set ppath_id = %d where path_id = %d" % (ppath_id, path_id))
    db.commit()
