#!/bin/bash

# Generate a directory with a year of 'snapshots' for testing
testdir="$1"
if [ -z "$1" ] ; then
	testdir="test"
fi

if [ ! -d "$testdir" ]
then
	mkdir "$testdir"
fi
cd "$testdir"
for (( i = 0 ; i < 1095 ; i++ ))
do
	dn=`date -d "today - $i days" +%Y-%m-%dT%H:%M:%SZ`
	mkdir $dn
	touch -d "today - $i days" $dn
done


